name: Golang CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write
  id-token: write
  
jobs:
  # CI:
  #   uses: infraspecdev/generic-workflows/.github/workflows/golang-ci.yml@main
  #   with:
  #     go-version: "1.22.6"
  #     use-private-module: true
  #     github-app-id: 968155
  #     ecr-repository: golang
  #   secrets:
  #     ASSUME_ROLE: ${{ secrets.ASSUME_ROLE }}
  #     APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

  CD:
    uses: infraspecdev/generic-workflows/.github/workflows/golang-deploy.yml@main
    with:
      ecs-cluster: "default-cluster"
      ecs-service: "nginx"
      task-definition-family: "nginx"
      image: "471112575944.dkr.ecr.ap-south-1.amazonaws.com/golang:sha-68f7ba9"
    secrets:
      assume-role: ${{ secrets.ASSUME_ROLE }}