name: Golang CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write
  id-token: write
  
jobs:
  lint:
    uses: infraspecdev/generic-workflows/.github/workflows/golang-ci.yml@main
    with:
      go-version: "1.22.6"
      use-private-module: true
      github-app-id: 968155
      ecr-repository: golang
    secrets:
      ASSUME_ROLE: ${{ secrets.ASSUME_ROLE }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
