name: Go - Build and Push

on:
  workflow_call:
    inputs:
      use-private-module:
        description: 'Flag to indicate if a private module should be used in the build'
        type: boolean
      ecr-repository:
        description: 'The name of the ECR repository to push the Docker image to'
        type: string
      aws-region:
        description: 'The AWS region where the ECR repository is located'
        type: string
      dockerfile:
        description: 'The path to the Dockerfile to use for building the Docker image'
        type: string
      platforms:
        description: 'The target platforms for the Docker image build (e.g., linux/amd64, linux/arm64)'
        type: string
      prefix:
        description: 'A prefix to use for the Docker image tags'
        type: string
      tag-type:
        description: 'The type of build (e.g., release, snapshot)'
        type: string
      github-app-id:
        description: 'The ID of the Github App'
        type: number
    secrets:
      ASSUME_ROLE:
        required: true
      APP_PRIVATE_KEY:
        description: 'The private key for the GitHub App'
        required: true


    outputs:
      image-tag:
        description: "Image tag output from build workflow"
        value: ${{ jobs.build.outputs.image-tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: read
      statuses: write

    outputs:
      image-tag: ${{ steps.image-tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          aws-region: ${{ inputs.aws-region }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        with:
          images: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=${{ inputs.tag-type }},prefix=${{ inputs.prefix }}-

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ inputs.github-app-id }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Build and push docker image to Amazon ECR
        uses: docker/build-push-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        with:
          context: .
          push: true
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:buildcache,mode=max,image-manifest=true,oci-mediatypes=true
          secrets: |
              GH_TOKEN=${{ steps.generate-token.outputs.token }}
   
      - name: Image Tag output
        id: image-tag
        run: |
          IMAGE_TAG=$(echo ${{ steps.meta.outputs.tags }} | awk -F':' '{print $NF}')
          echo "::notice title=Image tag::${IMAGE_TAG}"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV